'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('recipes',
    [
    {
      user_id: 1,
      name:'Instant Noodles',
      description:  "We makin' some maruchan",
      directions:   'You only need 5 minutes and some hot water. Pour, add your seasoning packet if any,wait, and enjoy',
      ingredient1:  'Hot water',
      ingredient2:  'Instant noodle packet',
      ingredient3:  null,
      ingredient4:  null,
      ingredient5: null,
      ingredient6: null,
      ingredient7: null,
      ingredient8: null,
      ingredient9: null,
      ingredient10: null,
      ingredient11: null,
      ingredient12: null,
      ingredient13: null,
      ingredient14: null,
      ingredient15: null,
      ingredient16: null,
      ingredient17: null,
      ingredient18: null,
      ingredient19: null,
      ingredient20: null,
      measurement1: '1 cup',
      measurement2: '1 serving',
      measurement3: null,
      measurement4: null,
      measurement5: null,
      measurement6: null,
      measurement7: null,
      measurement8: null,
      measurement9: null,
      measurement10: null,
      measurement11: null,
      measurement12: null,
      measurement13: null,
      measurement14: null,
      measurement15: null,
      measurement16: null,
      measurement17: null,
      measurement18: null,
      measurement19: null,
      measurement20: null,
      image: null,
    },
    {
      user_id: 2,
      name:'French Toast',
      description:  "Its time to make sugary eggy bread",
      directions:   'Mix the wets, add soak the old loaf in the mixture, melt the butter and fry it till golden brown, top with some powder sugar and syrup',
      ingredient1:  'Day old toast',
      ingredient2:  'Eggs',
      ingredient3:  'Milk',
      ingredient4:  'vanilla extract',
      ingredient5: 'Sugar',
      ingredient6: 'Butter',
      ingredient7: 'Powder Sugar',
      ingredient8: 'Syrup',
      ingredient9: null,
      ingredient10: null,
      ingredient11: null,
      ingredient12: null,
      ingredient13: null,
      ingredient14: null,
      ingredient15: null,
      ingredient16: null,
      ingredient17: null,
      ingredient18: null,
      ingredient19: null,
      ingredient20: null,
      measurement1: '2 slices of bread',
      measurement2: '2 Medium or 1 Large',
      measurement3: '1 cup',
      measurement4: '1 Tbsp',
      measurement5: '3 Tbsp',
      measurement6: '1 Tbsp',
      measurement7: "To your heart's content",
      measurement8: null,
      measurement9: null,
      measurement10: null,
      measurement11: null,
      measurement12: null,
      measurement13: null,
      measurement14: null,
      measurement15: null,
      measurement16: null,
      measurement17: null,
      measurement18: null,
      measurement19: null,
      measurement20: null,
      image: null,
    },
    {
      user_id: 3,
      name:'Toast',
      description:  "Givin' your everyday white bread some sun and fun",
      directions:   "Take your favorite Carb, place it into its personal suntan bed, then lather it with your favorite lipid",
      ingredient1:  'Fresh white bread',
      ingredient2:  'Butter',
      ingredient3:  null,
      ingredient4:  null,
      ingredient5: null,
      ingredient6: null,
      ingredient7: null,
      ingredient8: null,
      ingredient9: null,
      ingredient10: null,
      ingredient11: null,
      ingredient12: null,
      ingredient13: null,
      ingredient14: null,
      ingredient15: null,
      ingredient16: null,
      ingredient17: null,
      ingredient18: null,
      ingredient19: null,
      ingredient20: null,
      measurement1: 'However much you want',
      measurement2: '1 tbsp per slice',
      measurement3: null,
      measurement4: null,
      measurement5: null,
      measurement6: null,
      measurement7: null,
      measurement8: null,
      measurement9: null,
      measurement10: null,
      measurement11: null,
      measurement12: null,
      measurement13: null,
      measurement14: null,
      measurement15: null,
      measurement16: null,
      measurement17: null,
      measurement18: null,
      measurement19: null,
      measurement20: null,
      image: null,
    },
    {
      user_id: 4,
      name:'Gourmet Indomei',
      description:  "adding some love to your household indo",
      directions:   'Follow the instruction on the indomei and topped with a fried egg',
      ingredient1:  'Hot water',
      ingredient2:  'Indomei instant noodles',
      ingredient3:  "Egg",
      ingredient4:  "Oil",
      ingredient5: null,
      ingredient6: null,
      ingredient7: null,
      ingredient8: null,
      ingredient9: null,
      ingredient10: null,
      ingredient11: null,
      ingredient12: null,
      ingredient13: null,
      ingredient14: null,
      ingredient15: null,
      ingredient16: null,
      ingredient17: null,
      ingredient18: null,
      ingredient19: null,
      ingredient20: null,
      measurement1: '1 cup',
      measurement2: '1 serving',
      measurement3: '1 Large',
      measurement4: '1 Tbsp',
      measurement5: null,
      measurement6: null,
      measurement7: null,
      measurement8: null,
      measurement9: null,
      measurement10: null,
      measurement11: null,
      measurement12: null,
      measurement13: null,
      measurement14: null,
      measurement15: null,
      measurement16: null,
      measurement17: null,
      measurement18: null,
      measurement19: null,
      measurement20: null,
      image: null,
    },
    {
      user_id: 5,
      name:'Rice',
      description:  "everyone should know how to make rice",
      directions:   'Wash the rice till the water runs pretty clear, add your water, bring to a boil then set to simmer and leave it covered for 30mins on low',
      ingredient1:  'Rice',
      ingredient2:  'Water',
      ingredient3:  null,
      ingredient4:  null,
      ingredient5: null,
      ingredient6: null,
      ingredient7: null,
      ingredient8: null,
      ingredient9: null,
      ingredient10: null,
      ingredient11: null,
      ingredient12: null,
      ingredient13: null,
      ingredient14: null,
      ingredient15: null,
      ingredient16: null,
      ingredient17: null,
      ingredient18: null,
      ingredient19: null,
      ingredient20: null,
      measurement1: '1 cup',
      measurement2: 'Equal parts water to rice + 1/2 cup',
      measurement3: null,
      measurement4: null,
      measurement5: null,
      measurement6: null,
      measurement7: null,
      measurement8: null,
      measurement9: null,
      measurement10: null,
      measurement11: null,
      measurement12: null,
      measurement13: null,
      measurement14: null,
      measurement15: null,
      measurement16: null,
      measurement17: null,
      measurement18: null,
      measurement19: null,
      measurement20: null,
      image: null,
    },
    
  ]);
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('recipes',{},null)
  }
};
